/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SegmentosRouteImport } from './routes/segmentos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegmentosIndexRouteImport } from './routes/segmentos.index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as SegmentosSlugRouteImport } from './routes/segmentos.$slug'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminTestePagamentoRouteImport } from './routes/_authenticated.admin.teste-pagamento'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated.admin.pedidos'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminPedidosIdRouteImport } from './routes/_authenticated.admin.pedidos.$id'
import { Route as ApiPublicWebhookRedeTokenRouteImport } from './routes/api.public.webhook.rede.$token'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosRoute = SegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosIndexRoute = SegmentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SegmentosRoute,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRoute,
} as any)
const SegmentosSlugRoute = SegmentosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SegmentosRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminTestePagamentoRoute =
  AuthenticatedAdminTestePagamentoRouteImport.update({
    id: '/admin/teste-pagamento',
    path: '/admin/teste-pagamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/admin/pedidos',
    path: '/admin/pedidos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPedidosIdRoute =
  AuthenticatedAdminPedidosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPedidosRoute,
  } as any)
const ApiPublicWebhookRedeTokenRoute =
  ApiPublicWebhookRedeTokenRouteImport.update({
    id: '/api/public/webhook/rede/$token',
    path: '/api/public/webhook/rede/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/segmentos': typeof SegmentosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/teste-pagamento': typeof AuthenticatedAdminTestePagamentoRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/api/public/webhook/rede/$token': typeof ApiPublicWebhookRedeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/produtos': typeof ProdutosIndexRoute
  '/segmentos': typeof SegmentosIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/teste-pagamento': typeof AuthenticatedAdminTestePagamentoRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/api/public/webhook/rede/$token': typeof ApiPublicWebhookRedeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/segmentos': typeof SegmentosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/_authenticated/admin/teste-pagamento': typeof AuthenticatedAdminTestePagamentoRoute
  '/_authenticated/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/api/public/webhook/rede/$token': typeof ApiPublicWebhookRedeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contato'
    | '/login'
    | '/mcp'
    | '/produtos'
    | '/segmentos'
    | '/sitemap.xml'
    | '/solucoes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/produtos/$slug'
    | '/segmentos/$slug'
    | '/produtos/'
    | '/segmentos/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/pedidos'
    | '/admin/teste-pagamento'
    | '/admin/pedidos/$id'
    | '/api/public/webhook/rede/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contato'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/solucoes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/produtos/$slug'
    | '/segmentos/$slug'
    | '/produtos'
    | '/segmentos'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/pedidos'
    | '/admin/teste-pagamento'
    | '/admin/pedidos/$id'
    | '/api/public/webhook/rede/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/contato'
    | '/login'
    | '/mcp'
    | '/produtos'
    | '/segmentos'
    | '/sitemap.xml'
    | '/solucoes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/produtos/$slug'
    | '/segmentos/$slug'
    | '/produtos/'
    | '/segmentos/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/teste-pagamento'
    | '/_authenticated/admin/pedidos/$id'
    | '/api/public/webhook/rede/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  SegmentosRoute: typeof SegmentosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolucoesRoute: typeof SolucoesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicWebhookRedeTokenRoute: typeof ApiPublicWebhookRedeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos': {
      id: '/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof SegmentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/': {
      id: '/segmentos/'
      path: '/'
      fullPath: '/segmentos/'
      preLoaderRoute: typeof SegmentosIndexRouteImport
      parentRoute: typeof SegmentosRoute
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/segmentos/$slug': {
      id: '/segmentos/$slug'
      path: '/$slug'
      fullPath: '/segmentos/$slug'
      preLoaderRoute: typeof SegmentosSlugRouteImport
      parentRoute: typeof SegmentosRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/teste-pagamento': {
      id: '/_authenticated/admin/teste-pagamento'
      path: '/admin/teste-pagamento'
      fullPath: '/admin/teste-pagamento'
      preLoaderRoute: typeof AuthenticatedAdminTestePagamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pedidos/$id': {
      id: '/_authenticated/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIdRouteImport
      parentRoute: typeof AuthenticatedAdminPedidosRoute
    }
    '/api/public/webhook/rede/$token': {
      id: '/api/public/webhook/rede/$token'
      path: '/api/public/webhook/rede/$token'
      fullPath: '/api/public/webhook/rede/$token'
      preLoaderRoute: typeof ApiPublicWebhookRedeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminPedidosRouteChildren {
  AuthenticatedAdminPedidosIdRoute: typeof AuthenticatedAdminPedidosIdRoute
}

const AuthenticatedAdminPedidosRouteChildren: AuthenticatedAdminPedidosRouteChildren =
  {
    AuthenticatedAdminPedidosIdRoute: AuthenticatedAdminPedidosIdRoute,
  }

const AuthenticatedAdminPedidosRouteWithChildren =
  AuthenticatedAdminPedidosRoute._addFileChildren(
    AuthenticatedAdminPedidosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRouteWithChildren
  AuthenticatedAdminTestePagamentoRoute: typeof AuthenticatedAdminTestePagamentoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRouteWithChildren,
  AuthenticatedAdminTestePagamentoRoute: AuthenticatedAdminTestePagamentoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

interface SegmentosRouteChildren {
  SegmentosSlugRoute: typeof SegmentosSlugRoute
  SegmentosIndexRoute: typeof SegmentosIndexRoute
}

const SegmentosRouteChildren: SegmentosRouteChildren = {
  SegmentosSlugRoute: SegmentosSlugRoute,
  SegmentosIndexRoute: SegmentosIndexRoute,
}

const SegmentosRouteWithChildren = SegmentosRoute._addFileChildren(
  SegmentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  SegmentosRoute: SegmentosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolucoesRoute: SolucoesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicWebhookRedeTokenRoute: ApiPublicWebhookRedeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
