/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SegmentosRouteImport } from './routes/segmentos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegmentosIndexRouteImport } from './routes/segmentos.index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as SegmentosSlugRouteImport } from './routes/segmentos.$slug'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosRoute = SegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosIndexRoute = SegmentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SegmentosRoute,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRoute,
} as any)
const SegmentosSlugRoute = SegmentosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SegmentosRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/segmentos': typeof SegmentosRouteWithChildren
  '/solucoes': typeof SolucoesRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/solucoes': typeof SolucoesRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/produtos': typeof ProdutosIndexRoute
  '/segmentos': typeof SegmentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/segmentos': typeof SegmentosRouteWithChildren
  '/solucoes': typeof SolucoesRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contato'
    | '/produtos'
    | '/segmentos'
    | '/solucoes'
    | '/produtos/$slug'
    | '/segmentos/$slug'
    | '/produtos/'
    | '/segmentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contato'
    | '/solucoes'
    | '/produtos/$slug'
    | '/segmentos/$slug'
    | '/produtos'
    | '/segmentos'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contato'
    | '/produtos'
    | '/segmentos'
    | '/solucoes'
    | '/produtos/$slug'
    | '/segmentos/$slug'
    | '/produtos/'
    | '/segmentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  SegmentosRoute: typeof SegmentosRouteWithChildren
  SolucoesRoute: typeof SolucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos': {
      id: '/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof SegmentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/': {
      id: '/segmentos/'
      path: '/'
      fullPath: '/segmentos/'
      preLoaderRoute: typeof SegmentosIndexRouteImport
      parentRoute: typeof SegmentosRoute
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/segmentos/$slug': {
      id: '/segmentos/$slug'
      path: '/$slug'
      fullPath: '/segmentos/$slug'
      preLoaderRoute: typeof SegmentosSlugRouteImport
      parentRoute: typeof SegmentosRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
  }
}

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

interface SegmentosRouteChildren {
  SegmentosSlugRoute: typeof SegmentosSlugRoute
  SegmentosIndexRoute: typeof SegmentosIndexRoute
}

const SegmentosRouteChildren: SegmentosRouteChildren = {
  SegmentosSlugRoute: SegmentosSlugRoute,
  SegmentosIndexRoute: SegmentosIndexRoute,
}

const SegmentosRouteWithChildren = SegmentosRoute._addFileChildren(
  SegmentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  SegmentosRoute: SegmentosRouteWithChildren,
  SolucoesRoute: SolucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
